### ISSUE TITLE
Package uses session, but it is not declared as a dependency in package.js

### ISSUE THREAD

**Issue by Anima-t3d** [convexset/meteor-flow-router-tree#1]
``` javascript
if (!(Meteor.loggingIn() || Meteor.userId())) {
  var path = FlowRouter.current().path;
  if (path !== FlowRouter.path(loginRouteName)) {
    Session.set(sessionVariableNameForRedirectPath, path);
  }
  return FlowRouter.go(FlowRouter.path(loginRouteName));
}
```

I'm referring to [lines 355-379 in flow-router-tree.js](https://github.com/convexset/meteor-flow-router-tree/blob/c1f5cab7296c4186d56a38c4fb133ccd2e1240c4/packages/flow-router-tree/flow-router-tree.js#L355-L379)

Session needs to be added as a dependency in [package.js](https://github.com/convexset/meteor-flow-router-tree/blob/master/packages/flow-router-tree/package.js#L9)

Preferrably using imply: https://docs.meteor.com/api/packagejs.html#PackageAPI-imply

**Comment by convexset** [comment]
I'm lazy... send me a few lines of code to copy/paste.

**Comment by Anima-t3d** [comment]
Something like this:

``` javascript
Package.onUse(function (api) {
    api.versionsFrom('1.2.0.2');
    api.use([
        'ecmascript',
        'underscore',
        'check',
        'session',
        'kadira:flow-router@2.9.0',
        'kadira:blaze-layout@2.2.0',
        'convexset:package-utils@0.1.14',
        'convexset:match-extensions@0.1.1'
    ]);
    api.imply([
        'session',
        'kadira:flow-router@2.9.0'
    ]);
    api.addFiles(['flow-router-tree.js']);
    api.export('FlowRouterTree');
});
```

**Comment by convexset** [comment]
b5001d98eee21cc866e3f09c2f1919ecd6318736
